version: 2
updates:
  - package-ecosystem: npm
    directory: /twitter-openapi-typescript
    schedule:
      interval: daily
# - package-ecosystem: npm
#   directory: /twitter-openapi-typescript-generated
#   schedule:
#     interval: daily
