version: 2
updates:
  - package-ecosystem: npm
    directory: /twitter-openapi-typescript
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: npm
    directory: /twitter-openapi-typescript-generated
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
