inputSpec: twitter-openapi/dist/typescript/openapi-3.0.yaml
outputDir: .
npmName: twitter-openapi-typescript-generated
npmVersion: 0.0.6

# withoutRuntimeChecks: false
legacyDiscriminatorBehavior: false
# modelPropertyNaming: original
# stringEnums: true
# paramNaming: original
